# Generated by Django 4.1.7 on 2023-03-03 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('name', models.CharField(max_length=150)),
                ('mobile', models.CharField(blank=True, max_length=150)),
                ('images', models.ImageField(blank=True, null=True, upload_to='media')),
                ('city', models.CharField(help_text="Hozirda yashaydigan mazilingizni ko'rsating", max_length=50, verbose_name='Qaysi shaharda yashaysiz?')),
                ('street', models.CharField(help_text="Hozirda yashaydigan mahalla yoki ko'changiz nomini kiriting", max_length=50, verbose_name='Qaysi mahallada yashaysiz?')),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Accounts',
                'verbose_name_plural': 'Accounts',
            },
        ),
        migrations.CreateModel(
            name='Patsient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('personal_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.personalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('patsient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.patsient')),
                ('personal_info', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='user.personalinfo')),
            ],
        ),
    ]
