# Generated by Django 4.1.7 on 2023-03-03 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('name', models.CharField(max_length=150)),
                ('mobile', models.CharField(blank=True, max_length=150)),
                ('images', models.ImageField(blank=True, null=True, upload_to='media')),
                ('password', models.CharField(max_length=50)),
                ('city', models.CharField(blank=True, help_text="Hozirda yashaydigan mazilingizni ko'rsating", max_length=50, null=True, verbose_name='Qaysi shaharda yashaysiz?')),
                ('street', models.CharField(blank=True, help_text="Hozirda yashaydigan mahalla yoki ko'changiz nomini kiriting", max_length=50, null=True, verbose_name='Qaysi mahallada yashaysiz?')),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('name', models.CharField(max_length=150)),
                ('mobile', models.CharField(blank=True, max_length=150)),
                ('images', models.ImageField(blank=True, null=True, upload_to='media')),
                ('password', models.CharField(max_length=50)),
                ('city', models.CharField(blank=True, help_text="Hozirda yashaydigan mazilingizni ko'rsating", max_length=50, null=True, verbose_name='Qaysi shaharda yashaysiz?')),
                ('street', models.CharField(blank=True, help_text="Hozirda yashaydigan mahalla yoki ko'changiz nomini kiriting", max_length=50, null=True, verbose_name='Qaysi mahallada yashaysiz?')),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patsient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('name', models.CharField(max_length=150)),
                ('mobile', models.CharField(blank=True, max_length=150)),
                ('images', models.ImageField(blank=True, null=True, upload_to='media')),
                ('password', models.CharField(max_length=50)),
                ('city', models.CharField(blank=True, help_text="Hozirda yashaydigan mazilingizni ko'rsating", max_length=50, null=True, verbose_name='Qaysi shaharda yashaysiz?')),
                ('street', models.CharField(blank=True, help_text="Hozirda yashaydigan mahalla yoki ko'changiz nomini kiriting", max_length=50, null=True, verbose_name='Qaysi mahallada yashaysiz?')),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeniorDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('name', models.CharField(max_length=150)),
                ('mobile', models.CharField(blank=True, max_length=150)),
                ('images', models.ImageField(blank=True, null=True, upload_to='media')),
                ('password', models.CharField(max_length=50)),
                ('ccity', models.CharField(blank=True, help_text="Hozirda yashaydigan mazilingizni ko'rsating", max_length=50, null=True, verbose_name='Qaysi shaharda yashaysiz?')),
                ('street', models.CharField(blank=True, help_text="Hozirda yashaydigan mahalla yoki ko'changiz nomini kiriting", max_length=50, null=True, verbose_name='Qaysi mahallada yashaysiz?')),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.doctor')),
                ('nurse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.nurse')),
                ('patsient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.patsient')),
            ],
        ),
        migrations.AddField(
            model_name='nurse',
            name='patsient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.patsient'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='nurse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.nurse'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='patsient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.patsient'),
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('name', models.CharField(max_length=150)),
                ('mobile', models.CharField(blank=True, max_length=150)),
                ('images', models.ImageField(blank=True, null=True, upload_to='media')),
                ('password', models.CharField(max_length=50)),
                ('city', models.CharField(blank=True, help_text="Hozirda yashaydigan mazilingizni ko'rsating", max_length=50, null=True, verbose_name='Qaysi shaharda yashaysiz?')),
                ('street', models.CharField(blank=True, help_text="Hozirda yashaydigan mahalla yoki ko'changiz nomini kiriting", max_length=50, null=True, verbose_name='Qaysi mahallada yashaysiz?')),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.doctor')),
                ('nurse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.nurse')),
                ('senior_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.seniordoctor')),
            ],
        ),
    ]
