# Generated by Django 4.1.7 on 2023-03-03 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seniordoctor',
            old_name='ccity',
            new_name='city',
        ),
    ]
