# Generated by Django 4.1.7 on 2023-03-04 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                default=123456789,
                max_length=255,
                verbose_name="Telefon raqami",
            ),
            preserve_default=False,
        ),
    ]
