# Generated by Django 4.1.7 on 2023-03-03 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.nurse')),
                ('patsient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.patsient')),
                ('personal_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.personalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='SeniorDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.doctor')),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.nurse')),
                ('patsient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.patsient')),
                ('personal_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.personalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.doctor')),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.nurse')),
                ('senior_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.seniordoctor')),
            ],
        ),
    ]
