# Generated by Django 4.1.7 on 2023-03-03 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_ccity_seniordoctor_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='patsient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='user.patsient'),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='patsient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.patsient'),
        ),
    ]
