# Generated by Django 4.1.7 on 2023-03-04 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_user_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Telefon raqami"
            ),
        ),
    ]
