# Generated by Django 4.1.7 on 2023-03-03 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_doctor_seniordoctor_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='nurse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.nurse'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='nurse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.nurse'),
        ),
        migrations.AlterField(
            model_name='seniordoctor',
            name='nurse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.nurse'),
        ),
    ]
