# Generated by Django 4.1.7 on 2023-03-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('doctor_leader', 'Bosh shifokor'), ('doctor', 'Shifokor'), ('nurse', 'Hamshira'), ('citizen', 'Patsient'), ('admin', 'Admin')], default='nurse', max_length=255, verbose_name='Foydalanuvchi turi'),
        ),
    ]
