# Generated by Django 4.1.7 on 2023-03-05 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='User1Chat', to=settings.AUTH_USER_MODEL)),
                ('user2', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='User2Chat', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='user.chat')),
                ('suhbatdosh1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suhbatdosh1_messages', to=settings.AUTH_USER_MODEL)),
                ('suhbatdosh2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suhbatdosh2_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
