# Generated by Django 4.1.7 on 2023-03-06 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_chat_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='suhbatdosh1',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suhbatdosh1_messages', to='user.chat'),
        ),
        migrations.AlterField(
            model_name='message',
            name='suhbatdosh2',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suhbatdosh2_messages', to='user.chat'),
        ),
    ]
